w3c/presentation-api

Overview.src.html, index.html
Update @mfoltzgoogle 's pull request in the following ways:
* Rebased on top of w3c/presentation-api
* Added terminology items and references to respective external specs, highlighted usage of these terms in the algorithms seciton.
* Added a step in the Start Session section to bring up a browsing context and display the page on the presentation display.
* Rephrased and compacted availability monitoring section, trying to incorporate @mfoltzgoogle and @tidoust 's suggestions.
* Added step to trigger availability monitoring in the Start Session algorithm
=> Updated Mark's PR

Overview.src.html, index.html, xrefs/presentation.json
* APIs for interacting with Presentation.. => "API"
* opening browsing context
* close, send => own algorithms
* send TODO moved
* session property open-issue, still required?
* AvailableChange event reorg'ed
* Idioms => uppercase
* Definition of "presentation"
* session identifier => add "alphanumeric"
* Availability updating algorithm isolated
* Organizing section of onavailable change
** Define monitoring algorithm
** Define when to start and cancel monitoring
* Event handlers wording
* Replace "opener page" => opening browsing context
* removed .XXX style
* Padding before headings
=> Addressing Anssi's feedback, expanding the noted items

Overview.src.html, index.html
This new paragraph mentions the provenance of the spec, most important change
since publication by the CG, alerts users about missing or incomplete parts,
and invites them to check the list of issues on GitHub.
It builds on the text proposed by @anssiko.
Notes:
- the need for a custom paragraph comes from PubRules [1].
The Manual of Style [2] gives useful examples of points to address in this
custom paragraph, which I followed to some extent.
- a few other changes will be needed to convert the document into a "First
Public Working Draft". This will be the last changes made to the spec, when
the spec right before publication, when the spec is copied over to W3C space.
[1] http://www.w3.org/2005/07/pubrules?year=2015&uimode=filter&filter=Filter+pubrules&filterValues=form&docstatus=fpwd-wd-tr …
=> Added a custom paragraph in Status of This Document section (#47)

Overview.src.html, index.html, releases/FPWD.html
The group's Charter defines a custom Document License [1] the documents produced by this group should use. To that end, I updated the Editor's Draft as well as the FPWD snapshot in staging accordingly.
@tidoust Pubrules checker naturally does not understand this custom Document License, so this needs to be checked manually.
[1] http://www.w3.org/2014/secondscreen/charter.html#doclicense
=> Use the custom W3C Document License defined in the Charter

Overview.src.html, index.html, releases/FPWD.html
Note the commit also changes the copyright date to 2015.
The custom copyright notice noted in the charter of the working group is no longer useful now that the W3C Document License has been updated to license code components under a W3C Software License. The group may thus roll back to the regular pub-rule compliant copyright notice, which will achieve the same effect.
Addresses #55.
=> Rolled back Copyright notice to the usual one

releases/FPWD.html
We should update the canonical link relationship to point to the latest spec (aka Editor's Draft) to make sure search engines prefer the latest spec over the dated snapshot(s). It is a known problem that people who search for the specifications using their favourite search engine will often end up reading old snapshot releases rather than the latest.
We fix this for the FPWD in staging (now published) by changing the canonical link relation to point to the latest.
A generic solution to this problem is to adopt the new publication workflow at W3C which allows the group to automatise its TR publications and release as often as needed to keep the TR releases fresh. The group may want to consider adopting the new workflow when the initial kinks are gone (see the alpha release announcement at …
=> Update the canonical link relation to help search engines find the latest

Overview.src.html, index.html
* Code conventions per Douglas Crockford (http://javascript.crockford.com/code.html). I know this is a matter of taste, but Crockford has a good taste as he knows The [JavaScript] Good Parts ;-)
* Factor out `endSession()` from `setSession()` to make the `.then(setSession).catch(endSession)` even more concise.
@drott @louaybassbouss Please review, and feel free to merge if this does not introduce any bugs and the style is digestible to you.
Related: https://github.com/w3c/presentation-api/pull/64
=> Example code conventions, factor our endSession() from setSession()

Overview.src.html, index.html
missing "(" and ")" added to line:
localStorage && (localStorage["presId"] = session.id);
=> Fix syntax error in examples

Overview.src.html, index.html, xrefs/presentation.json
While trying to land the first CL implementing postMessage in Blink the reviewer noticed that postMessage() is already used in numerous other APIs and has a different signature. PresentationSession.postMessage() is a copy of WebRTC DataChannel send() and Mark Foltz's proposal also named the method send() (see https://github.com/w3c/presentation-api/issues/46).
Mozilla has implemented it as a send() too (https://bugzilla.mozilla.org/attachment.cgi?id=8527264&action=diff#a/dom/webidl/PresentationSocketChannel.webidl_sec1).
The Blink CL with the context is here: https://codereview.chromium.org/1002293005
P.S. Also accidentally removed some trailing whitespace it seems.
=> Renamed postMessage() to send() to align with WebRTC DataChannel

Overview.src.html, index.html
A minor fix to the examples: the `data` is an attribute of the event.
=> 'data' is an attribute of the event

Overview.src.html, index.html
A demo link is at http://avayvod.github.io/nits.html
The removal of the unused 'origin' step from the PresentationSession.send() was discussed at the F2F as part of the Issue #63
=> Fixed typos and removed the 'origin' extraction step from the send() algorithm

Overview.src.html, index.html
Updates spec for proposed resolution of Issue #76.
=> Add NOTE clarifying presentation URL scheme support

Overview.src.html, index.html
This PR drafts the Security and Privacy Considerations following discussion in #45.  @tidoust and others, please review.
=> Issue #45: Security and Privacy Considerations

Overview.src.html, index.html
This PR implements the action from #39: drop id from startSession() without strong use case, the UA generates the id
=> Issue #39: Drop presentationId from startSession

.travis.yml, ECHIDNA, Makefile, Overview.src.html, index.html
This commit should contain all updates needed to be able to publish working
drafts to /TR/ space at W3C on a semi-automated basis.
The basic principle is to use a dedicated "TR" branch where we generate the
Working Draft to publish. Any push to that branch will trigger Travis CI
(provided it is enabled on the repository, obviously) that will, in turn,
send a publication request to Echidna at W3C with the right parameters.
Actually publishing the spec from a local checkout of the gh-pages branch
should look like:
git checkout TR
git merge gh-pages
make wd
git add releases/WD.html
git commit
git push w3c TR
Using a separate branch is not stricto senso necessary. I chose that option:
1. to have Working Drafts remain somewhat hidden on GitHub, the gh-pages
branch will only contain the …
=> Spec pubrules and Echidna compliant, WD generation semi-automated

Overview.src.html, index.html, xrefs/presentation.json
This PR updates the spec to be more explicit about the in-sequence and reliability semantics of the messaging channel, and should close out Issue #46.
This does not seem controversial, so will merge right away.
Fixing the cross reference will be addressed later with a pull request to whatwg/xref.
=> Issue #46: Define a bi-directional data channel between opening and presenting browsing contexts

Overview.src.html, index.html, xrefs/presentation.json
Modified version of PR by @obeletski to implement resolution of #34.  Also impacts #19.
=> Updated version of PR#119: Initial description of session creation and monitoring in presenting

uc-req.md
Issue #68: Use cases and Requirements document updated as following:
* Update "UC02: Video and image Sharing" to derive requirement "REQ03: Resuming presentation".
* Add missing requirement "REQ04: Joining presentation". This is derived from the multiplayer game use case
* Update the requirements derived from each use cases (each requirement is addressed in at least one use case).
* Start numbering for non-functional requirements with NF-REQ01. This allows us the add new functional and non-functional requirements without mixing the numbers.
TODO: in Overview.src.html change "https://github.com/w3c/presentation-api/blob/gh-pages/uc-req.md#req08-power-saving-friendly"  into "https://github.com/w3c/presentation-api/blob/gh-pages/uc-req.md#nf-req01"
=> Issue #68: Use cases and Requirements document updated

Overview.src.html, index.html
In particular, "queuing" was spelled "queing" and a couple of references
to "queue a task" did not link back to the definition.
The "monitoring incoming presentation sessions" algorithm was not
properly referenced either.
Note that I used "queueing" instead of "queuing" because http://xkcd.com/853/
=> A few typos and links to term definitions fixed

uc-req.md
Update to reflect the fact that we resume connection to the presentation and not the presentation itself, 
https://github.com/w3c/presentation-api/issues/68
=> Update to resuming requirement

Overview.src.html, index.html, xrefs/presentation.json
The interface name is exposed in the global object so having it prefixed
with Presentation is probably safer. Also, it prevents the Presentation
API from taking ownership of the generic 'Availability' interface name.
=> Rename Availability interface to PresentationAvailability.

Overview.src.html, index.html
This is also including a typo fix.
=> Specify the DOMException name when rejecting a getAvailability() call.

index.html
=> Introduce PresentationRequest and defaultRequest.

index.html
Make use of the [syntax highlighter][1] of ReSpec.
[1]: https://www.w3.org/respec/ref.html#highlight
=> Use syntax highlighting in the examples

index.html
Like most features showing a prompt, it should be bound to a user gesture, otherwise this is going to lead to very confusing UX.
@avayvod @anssiko @mfoltzgoogle PTAL
=> PresentationRequest.start() requires a user gesture.

index.html
ReSpec has a feature that allows to pull in data using the GitHub API. This PR makes use of that feature and pulls open issue data directly from GH issues into the spec. This change should make it easier for us to keep the spec and GH issues in sync, as the latter will be the canonical source for all issue data. Any changes done to the GH issues (specifically, its topic or the first comment) will be automatically pulled into the latest spec.
For example, the following markup in the ReSpec source:
<div class="issue" data-number="35"></div>
Is turned into the following markup automatically:
<div class="issue" id="issue-35">
<div class="issue-title" aria-level="5" role="heading" id="h-issue1">
<a href="https://www.github.com/w3c/presentation-api/issues/35">
<span>ISSUE 35</span></a>: …
=> Pull in issue tracker data using GitHub API

index.html
With a (lazy) copy/pasting of example 1 I found a little typo : a missing parenthesis.
=> Add missing parenthesis in example 1 code

Makefile
This said, I'm not entirely sure why we use ```tidy-html5``` as the name of the binary while ```tidy``` is the output of building the tool from the repository. Am I doing something wrong?
=> Use TIDY instead of TIDY-HTML5 to make it settable in from ENV.

build/tidyconfig.txt
Recent version 5.0.0 of tidy seems to treat ampersands a bit differently. It drops the escaping of non-ambiguous ampersands in particular.
That is technically correct in HTML5, see the relevant spec definition:
http://www.w3.org/TR/html5/syntax.html#syntax-ambiguous-ampersand
I would personally prefer tidy not to update entitites that we chose to escape though. The "preserve-entities" setting does just that.
This was initially raised in #164:
https://github.com/w3c/presentation-api/issues/164#issuecomment-133460718
FWIW, the change in Tidy may be due to:
https://github.com/htacg/tidy-html5/issues/207
=> Set tidy "preserve-entitites" config flag to preserve &amp; escaping

index.html
In other words, if there is a discovery happening which already found a device, getAvailability() should be resolved with true.
Fixes #161
=> getAvailability() should return true if the list of displays isn't empty.

index.html
@mfoltzgoogle This is a workaround to hide the (currently too verbose) issue summaries pulled from GH. If this feature is liked by others we should bake this into ReSpec as a configuration option. In the interim, this CSS should do.
=> Hide issue summaries pulled from GH

index.html
ReSpec keeps the "for" (and "link-for") attributes in the spec it generates, but these attributes are not valid in HTML5, so the markup validator reports errors accordingly and the specification cannot be published to /TR/.
This is a temporary fix while the bug gets fixed on ReSpec:
https://github.com/w3c/respec/issues/483
(Note that I also removed the duplicated "issueBase" entry that appeared
in ReSpec config)
=> Added ReSpec postprocessing to remove "for" attributes

.travis.yml
Travis configuration meant that the editor's draft in the default "gh-pages" is being published to /TR/. However, it should rather be the editor's draft in the "TR" branch.
In other words, the URL to give to Echidna should not be:
https://w3c.github.io/presentation-api/ECHIDNA
... but rather:
https://rawgit.com/w3c/presentation-api/TR/ECHIDNA
This commit updates the URL in the Travis configuration. Note that I also updated the information associated with the publication token stored on W3C servers to expect "https://rawgit.com/w3c/presentation-api/TR/" source URLs
=> [publication] Updated URL passed to Echidna to use right Git branch

index.html
=> Make session a required argument when constructing a PresentationSessionConnect.

index.html
This is moving around some spec definitions to apply on
PresentationReceiver instead of Presentation, the examples have been
changed and navigator.presentation.receiver has been defined.
Fixes #91.
=> Add PresentationReceiver and navigator.presentation.receiver to access it.

index.html
As things stood, the steps to "start a presentation session" required the UA to create a valid presentation session identifier before creating the task C to navigate the receiving browser context.
However, the presentation session identifier will only be added to the set of presentations when C completes. If the user calls "start" again in the meantime, a UA that would generate the same valid presentation session identifier for the second presentation session would correctly follow these steps (that identifier would not yet be in the set of presentations), but this would create two PresentationSession with the same identifier.
Also, the new PresentationSession S is actually not needed until C completes successfully.
This commit moves the creation of the presentation session identifier and …
=> Reorder start steps to create session only when needed

index.html
Addresses Issue #35.  
This PR adds terminate() to PresentationSession and defines behavior for it and for close().  It also renames the disconnect state to closed.
The definitions will remain a bit awkward until the two conformance classes are better defined, as the behavior is asymmetrical.
=> Adds terminate() to PresentationSession and defines behavior for it.

index.html
This addresses Issues #152  and #171 by renaming "presentation session" to "presentation connection," `PresentationSession` to `PresentationConnection`, and the events renamed as in #152. 
For the most part the changes are mechanical; however, in some places, the term "presentation connection" did not make sense and was replaced by "presentation."
Also, this PR has the side effect of redefining the presentation ID and URL as inherent to the presentation, not of an individual connection to the presentation. They continue to be provided as readonly properties on each `PresentationConnection.`  The algorithms may need some adjustment to ensure that matching and iteration based on URL and ID make sense.
=> Renames PresentationSession to PresentationConnection

index.html
This PR defines two conformance classes for the specification to address Issue #93:
* A controlling user agent provides the controlling browsing context and its associated interfaces/objects.
* A receiving user agent provides the receiving browsing context and its associated interfaces/objects.
The PR makes normative statements about each of them where it makes sense to do so.  In most cases I say that a particular user agent SHOULD or MUST implement a certain interface in the corresponding browsing context - perhaps there is a better way to make these normative statements.
I didn't try to regroup the definitions by conformance class in this PR, but that might make the spec read better in the long run.  For example, PresentationConnection is required by both UAs.  It may be clearer to …
=> Defines two conformance classes for the specification

index.html
* Update the spec to use the more concise style for exceptions that is adopted by contemporary specifications.
* Add definitions for the exceptions used by this spec to Terminology.
* Tidy.
=> Use concise, contemporary style for exceptions

index.html
This PR resolves #14 given the feedback from TAG that there won't be a well defined "private browsing mode" in the near future (action item http://www.w3.org/2015/10/29-webscreens-minutes.html#action01).
It also addresses #148 to simplify the steps to start a presentation.  It make it clearer that monitoring the list of presentation displays and asking user permission can happen in parallel - otherwise implementations that don't use background monitoring won't be very usable.
=> Adds an algorithm for creating a receiving browsing context

index.html
This PR reorganizes the API section to be more logical, starting from the top level interface and working down.  It also improves naming for a couple of the algorithms.
The new outline:
```
6. API
6.1 Common idioms
6.2 Interface Presentation
6.2.1 Controlling user agent
6.2.2 Receiving user agent
6.3 Interface PresentationRequest
6.3.1 Constructing a PresentationRequest
6.3.2 Starting a presentation
6.3.3 Reconnecting to a presentation
6.3.4 Establishing a presentation connection
6.3.5 Event Handlers
6.4 Interface PresentationAvailability
6.4.1 The set of availability objects
6.4.2 The list of available presentation displays
6.4.3 Monitoring the list of available presentation displays
6.4.4 Interface PresentationConnectionAvailableEvent
6.5 Interface PresentationConnection
6.5.1 Sending a …
```
=> Reorder api

index.html
* Update Example 6 with the following changes introduced in https://github.com/w3c/presentation-api/pull/221: `receiver.getConnection()` and `receiver.getConnections()` were removed and replaced by a Promise-returning [`connections`][1] attribute.
* Add `<dfn>`s for `PresentationReceiver.connections` and `PresentationConnectionList.connections`.
* (Some noise due to tidy.)
@mounirlamouri @mfoltzgoogle PTAL.
[1]: https://w3c.github.io/presentation-api/#idl-def-presentationreceiver
=> Sync example 6 with changes in #221, rename PresentationReceiver.connections to .connectionList

index.html
This PR addresses the following issues:
* https://github.com/w3c/presentation-api/issues/214
* https://github.com/w3c/presentation-api/issues/149
* https://github.com/w3c/presentation-api/issues/198
* https://github.com/w3c/presentation-api/issues/216
Summary of changes:
* Adds a new "connecting" state to the PresentationConnection (Issue #214)
* Adds per-state event handlers `onconnected`, `onclosed` and `onterminated` to replace `onstatechange`
* Adds a `PresentationConnectionCloseEvent` and `PresentationConnectionCloseReason` with details on why a connection was closed, including an error in the underlying message transport (Issue #149).
* Refine example code and algorithms to clarify initial presentation states and ensure message sending happens at the right time.  (Issue #198, Issue …
=> Adds a new "connecting" state and per-state event handlers.

index.html
Addresses #222 with "option 2" by clarifying the current definition.
=> Defines behavior for terminate() in controlling and receiving contexts

index.html
This should address issue #231.
In particular, "queue a task" is now only used to schedule events and to create a synchronization point between algorithms or parts of algorithms that run in the background and the event loop, e.g. to update property values on objects exposed to JavaScript code.
The "close a presentation connection" algorithm could perhaps be further improved: as things stand, it gets closed both as part of the event loop when "close" is called or when some connection error is detected in the background. In the former case, it should update the presentation connection state immediately. In the latter case, it should only update the presentation connection state as part of a proper task. I updated the prose that called this algorithm from the background to add a "queue a …
=> Algorithms updated to use "queue a task" only when needed

index.html
"Fire a simple event" is now used for all events that inherit from Event.
"Fire an event" is now used for events that inherit from one of the event interfaces defined in the spec. The prose is a bit more verbose in that case to clarify that the event is trusted, does not bubble and
non cancelable. I stuck to the prose used in HTML5 but we could perhaps define a new term such as "fire a custom event" to make things more concise.
The part that talks about the "connectionavailable" event on the PresentationReceiver interface is not very clear because there is no good way to reference the PresentationConnectionList instance associated with the PresentationReceiver object right now, but that should be handled as part of #193.
=> Fixed use of "fire an event" and "fire a simple event" in the spec

index.html
This is based on PR #238 but somewhat simplifies the two parts of the close algorithm and how they are invoked.  The first part signals the destination browsing context that the connection is closing and passes the reason (close or wentaway). The second part queues a task to change the connection state and fire the close event.
I wonder if we should change state before queueing a task on the event loop to avoid re-entrancy, to ensure correct behavior when calling close() then close() again (or another API method that checks the PresentationConnection state).
=> Updated version of PR #238

index.html
This is an attempt to clarify the closing procedure, in particular to split it into two separated procedures:
1. the user agent starts closing the underlying connection, signaling its plan to the other end.
2. the user agent actually fires the "closed" event when the underlying connection is closed.
The first step eventually calls the second when the underlying connection is marked as "closed".
The different possibilities that call the first step are:
- presentation connection could not be established
- close() was called
- a PresentationConnection object S is being discarded
The different possibilities that directly call the second step are:
- the underlying connection has been closed
- unrecoverable error while sending a message
- unrecoverable error while receiving a message
- signal …
=> Split the "close" algorithm into "closing" and "close" procedures

index.html
This is a set of editorial changes to improve the use of references and variable names in the spec.
I added possible definitions for the different presentation connection states.
All references to connection states and event names should now link back to
the definitions of these terms. This has the advantage of clarifying when
"closed" is used to mean the presentation connection state, the reason why
a connection was closed, or the event fired when the connection is closed.
The spec also used a combination of `<code>`, `<em>` and `<var>` to refer to variables
in different places. It should now only use `<code>` for interface, property,
event names, and code examples; and use `<var>` to refer to variable and parameter
names.
ReSpec confused the term "presentation" defined in Common idioms …
=> Added enum and event definitions, <var> for variables, fixed references

index.html
The procedure was removed when sections were reordered in December, probably
by accident:
https://github.com/w3c/presentation-api/commit/e7ab2291bbdf47406a68ea0a115f0ba682084b7a#diff-eacf331f0ffc35d4b482f1d15a887d3bL1143
This commit brings the procedure back into the spec.
Note I slightly updated the text to fix the use of <var>, <em> and <code>.
This should fix issue #246.
=> Re-inserted the getAvailability procedure

index.html
Addressing Issue #80:
* Updates the security section with the resolution [1] around mixed content.
* Elaborates the circumstances in which an additional user agent can connect to a presentation.
[1] https://www.w3.org/2015/10/29-webscreens-minutes.html#action07
=> Update security requirements for resolution around mixed content.

index.html
@mfoltzgoogle This is an attempt to Fix #211. Please review, and see if this matches your expectations. 
I defined "arraybuffer" as default since it seems to be a more future proof type that more and more APIs are able to consume. I also added a non-normative note borrowed from the WebSocket spec, mostly to clarify the behaviour to web developers.
=> Fix #211: Define binaryType default value and get/set behaviour

index.html
This PR addresses two issues:
- #223: Implementation guideline: users should have a way to know which origin is being presented at any time
- #224: Think more about privacy implications in multi-user scenarios
It adds a guideline that controlling user agents should display the origin of the URL that is to be presented.   It also adds guidelines about notifying the user when there are multiple parties that can control of a presentation.
=> Additional UI guidelines for user agents

index.html
I split the "set of presentations" into a "set of controlling presentations" and a "set of incoming presentations". The former set is a singleton shared across the browsing contexts running in the controlling user agent (and possibly published to other user agents). The latter set is per receiving browsing context.
I also dropped the description of tuples that defined the set of presentations. Unless I missed something, all the information in these tuples is actually exposed by the presentation connection object.
The prose makes it clear that all presentation connections share the same URL and ID in the receiving context.
The reconnect() algorithm was also updated to cover the case where a PresentationConnection has already been created in the current context for the same URL and …
=> Split "set of presentations" into controlling/receiving sets

index.html
This PR attempts to fix the remaining open issues in the Security and Privacy section enumerated in issue https://github.com/w3c/presentation-api/issues/45#issuecomment-178288674. These issues were blocking the [wide review WD][1] publication.
We will continue to improve the Security and Privacy sections based on new information received from horizontal reviews, and can reopen issues #45 when new information resurfaces.
[1]: https://github.com/w3c/presentation-api/milestones/wide-review-WD
=> Complete Security and Privacy section

index.html
Updates to the Status of This Document section of the document to point out the main changes since last publication, and calls out for a wide review of the document, as agreed in #244.
I mentioned a couple of issues (passing language settings and congestion control mechanism) as examples of remaining issues. Let me know if you feel that comes out of the blue and if the text should rather remain generic.
I noted exchanges with other W3C groups but did not explicitly list the horizontal reviews that have already been completed. I do not think they need to appear in the Status of This Document directly. We'll be able to point relevant people to these reviews when we consider transitioning to Candidate Recommendation.
PS: I used the undocumented "sotdAfterWGinfo" ReSpec flag to have the …
=> Updates to SoTD to invite wide review of the document

index.html
Renamed `connected` into `connect`, `closed` into `close` and `terminated` into `terminate` as suggested.
Note I had to introduce a namespace to distinguish the `close`/`terminate` methods from the eponymous events.
This commit also contains a minor fix to references to `connectionavailable`: it is defined once for `PresentationConnection` and once for `PresentationConnectionList`. Unqualified references go the first definition, but some of them should actually reference the second one. All references are now explicit as to which definition they target.
=> Drop use of passive form for event names (issue #256)

index.html
Addresses #205 (Specify whether properties of the Presentation are left undefined).  This makes it clear that the defaultRequest and receiver attributes should be null in user agents that implement one conformance class but not the other.
=> Clarifies handling of Presentation attributes.

index.html
The reconnect procedure no longer fires a "connectionavailable" event in the case when it finds a matching PresentationConnection for the current browsing context.
Fixes issue #259.
=> Do not trigger "connectionavailable" on reconnect for same presentation

index.html
This addresses #18 (Define reconnection for cross-page navigation on presenting user agent) by specifically terminating the presentation when navigation is attempted (other than by fragment identifier).  It also spells out the other circumstances in which a presentation is to be terminated. This list may not be  comprehensive; please point out anything missing.
Reading this, it looks like there are three distinct algorithms:
1. What happens when a controller terminates the presentation
2. What happens to the presentation
3. How connected controllers should respond to the terminated presentation
Perhaps it would be clearer to split 2 and 3 into separate sections.  Thoughts?
=> Clarifies when and how presentations are terminated

index.html
* Split interface Presentation IDL into partials to make testing easier (fixes #230)
* Clarify the `defaultRequest` attribute returns null in a receiving browsing context
@mfoltzgoogle @louaybassbouss Please review.
=> Split interface Presentation IDL into partials

index.html
The custom styles that we had for examples should no longer be needed, and the ones for IDL declarations cause the "WebIDL" banner to appear truncated.
Also fixed the structure of the Security and privacy considerations section, as ReSpec needs <section> tags to detect the headings and build the appropriate Table of Contents.
=> Styles adjusted for new official 2016 stylesheet

index.html
This PR adds a note to the section discussing `Presentation.defaultRequest` discussing considerations for the tap-to-present case, where presentation initiation and display selection happen at the same time.  I didn't try to patch the start-a-presentation algorithm to bypass the permission dialog- some discussion in the issue coming.
It also includes some copyediting on the previous note for user agents that don't support presentation via default request.
=> Addresses Issue 86: Define algorithm for browser initiated presentation using default presentation URL

index.html
This PR implements the proposed actions from Issue #218.  Specifically it:
* Adds advice to Web authors for localized strings
* Adds example code for transmitting a localized string and inserting it into the presentation
* Adds a requirement to use language preferences to request presentation resources
=> Adds spec language around localization

index.html
This is pull request for the pull request #277...
I have the following comments on PR #277:
1. The definition of the set of availability objects still asserts that `availabilityUrl` is the parameter passed to `getAvailability()`. That's an old remain of some past version where `getAvailability()` indeed took a parameter.
2. Getting the `connectionList` attribute creates a new `PresentationConnectionList` instance for each call, whereas I would assume we would rather return the same instance each time.
3. Getting the `connectionList` attribute always returns a promise that is immediately resolved. I believe the reason why we want a Promise in the first place is to ensure that the app gets a `connectionList` with at least one presentation connection in it (the one that gave birth to the …
=> Updates to PR #277 that addresses issues #254, #269, #273

index.html
This PR makes minor spec changes to address outstanding issues.
#254: When is the first presentation connection created in the receiving browsing context?
#269: Only allow one PresentationAvailability per PresentationRequest
#273: PresentationConnectionClosedEventInit.message needs to have a default value
=> Address issues #254, #269, #273

index.html
Addresses the following:
* Issue #253: Have the receiving browsing context generate the presentation identifier?
* Issue #279: Specify the algorithm for generating a presentation identifier
This change adopts the UUID algorithm from RFC 4112.  This is also used for MediaStream.id in the getUserMedia spec.
=> Establishes the algorithm for generating the presentation id.

index.html
The "start a presentation" algorithm was phrased against the controlling user agent, but some of the last steps (e.g. "Navigate R to presentationUrl") are actually to be performed by the receiving user agent. Similarly, the "create a receiving browsing context" algorithm mostly applied to the receiving user agent, but the first step was to be performed by the controlling user agent.
This commit ensures that the subject remains the same throughout the steps of these algorithms. The underlying goal is to ensure that algorithms can be linked back to one and only one conformance class, to ease testing.
Additional notes:
1. The controlling UA may want to wait for an ack between the step where it tells the receiving UA to create the receiving browsing context and the step where it establishes …
=> Clarified which UA performs the receiving browsing context step

index.html
This change makes explicit that the presentation id should be passed from the controlling user agent when creating a presentation (receiving browsing context), and that the id of incoming presentation connection requests must match.
=> Pass the presentation identifier when starting a presentation.

index.html
The reasons are:
- navigator.presentation returning null only in this edge case will lead
to bugs because developers will not expect this;
- we already have failure mode for all the methods;
- a malicious iframe could hold a Presentation instance if the embedder
where to have the sandbox flags not set properly for a short period of
time (eg. load race condition).
This change also does:
- add mixed security check for getAvailability() so we don't waste
resources listen for availability when not needed;
- fix editorial issues whith mixed security check where the steps were
not stopped.
=> Reject when sandbox blocks the feature instead of not exposing.

index.html
The <dfn> tags for "throw" were incorrectly surrounding "term" instead of "throw".
Also, as alluded to in #295, "NotAllowedError" is only defined in "WebIDL (Second Level)", and the spec referenced "WebIDL Level 1". I'm not clear at this stage whether "NotAllowedError" will make it to Level 1, but it seems better to reference Level 2 in the meantime.
=> Fix link to WebIDL "throw", update ref to WebIDL to target Second Level

.travis.yml
The "language" key is mandatory but our build does not need a Node.js environment. The "generic" value should tell Travis CI to use a simple bash environment to run the "curl" request. In turn, this should make all nvm related messages disappear from build logs.
I also dropped the "script" key since it is not needed (it might have been in the past) and does not do anything useful.
=> Switched to "generic" language in Travis CI to avoid warnings (#265)

index.html
I updated the acknowledgements list, taking into account contributions to the specifications, GitHub issues, and horizontal reviews. Hopefully I did not miss anyone.
I also dropped the remaining "issue" blocks and marked the use cases section, the examples section and the security guidance section as informative sections.
=> Updated acknowledgements list (#301), marked non-normative sections

index.html
Resolves Issue #228: GitHub API failing, which leads to ReSpec failures.  We have no more GitHub issues referenced in the spec, so we don't need this any more :-)
=> Issue #228: Remove GitHub issue code.

uc-req.md
Addresses Issue #242: Describe the use cases for terminate vs close
This PR adds a requirement for terminating a presentation, and updates the use cases to show two scenarios where it would be used.
There are already use cases tagged with the requirement for signalling disconnection (i.e. close) so I did not add or update any use cases for it.
=> Add requirement and use cases for terminate presentation

index.html
[Created a new branch to get a clean PR]
This PR implements a proposed resolution for Issue #99; see https://github.com/w3c/presentation-api/issues/99#issuecomment-221434513
It adds a note to handle Window functions that require user input on the receiving user agent, especially when they block (i.e. alert())
=> Addresses APIs with user input on receiving user agent (Issue #99)

index.html
As discussed during the F2F, the working group needs to agree on exit criteria for the Candidate Recommendation phase before it may publish the spec as Candidate Recommendation. I took an action at the F2F to craft such criteria:
http://www.w3.org/2016/05/24-webscreens-minutes.html#action09
The usual criteria (also defined in our charter) are to have, for each conformance class, two independent interoperable implementations of each feature.
On top of that, I propose to add the need to demonstrate that there are implementations of the 1-UA mode and of the 2-UA mode for receiving user agents, because we expect to see both modes supported in practice.
This pull request introduces a "CR exit criteria" appendix that details these criteria. The wording is based on other specs, e.g.:
- CSS …
=> CR Exit criteria

index.html
This PR implements parts of the resolution for Issue #275: User Data Controls in Web Browsers guidelines.    It also updates the list of site data to reflect implementation  status in the receiving user agent.
The parts remaining to be done include:
- Add a non-normative link to a reference list of site data when available.
- Add some text for Web Workers and Service Workers.  I would like to give this some more thought and possibly punt to separate issue.
=> Partially addresses Issue 275

index.html
This PR addresses Issue #311 (Add presentation request URL fallback mechanism).  It modifies the PresentationRequest constructor to take an array of URLs each of which will be considered in order when starting or connecting to a presentation.
This necessitated several changes, including:
- Updating example code
- Updating interfaces, including adding a `url` property to PresentationConnection so the caller knows what is being presented
- Updating the set of availability objects to have a list of URLs per object
- Updating the list (set?) of available presentation displays to keep track of which displays are compatible with which URLs so the start algorithm can choose the appropriate URL for the chosen display
- Various other algorithm and wording updates
@mounirlamouri @tidoust @sicking …
=> Updates PresentationRequest to take multiple URLs

index.html
This addresses Issue #318: Clear service worker's persistent storages in a receiving browsing context. Also, this PR refers to isolating window clients and worker clients associated with the receiving browsing context from the other browsing contexts, for interoperability between 1-UA and 2-UA.
PTAL
=> Addresses Issue #318

index.html
Preparing the document for publication as Candidate Recommendation, I noticed that the spec did not reference the DOM standard, whereas it uses some of its interfaces.
This update completes the list in the terminology with (base) IDL terms that the specification references such as EventTarget, EventHandler, etc.
Note it is strongly recommended to sort out the list of normative references before publication as Candidate Recommendation (any change to the list of normative references is by definition "normative", and normative changes to a Candidate Recommendation normally require another publication as Candidate Recommendation).
@anssiko or @mfoltzgoogle, could you review this as soon as possible and merge? Thanks!
=> Missing interface terms and reference to DOM standard added

index.html
The update clarifies the changes made to the specification since last publication. It asserts that no features are flagged as at risk, and that sandboxing definitions are expected to move to HTML.
This should match what the group agreed to. I'll take the liberty to merge this pull request in the draft CR spec that I'm currently preparing. Let me know as soon as possible if changes are needed.
=> Updated SoTD for publication as Candidate Recommendation

index.html
Addresses Issue #325: PresentationConnection.url should be optional? 
See the comment there for the rationale for this change.
Since there is no way to get a usable PresentationConnection other than through the PresentationAPI, and the API sets the ID for all connections, I don't believe this change in semantics will affect any Web content.
=> Make PresentationConnection.id mandatory.

index.html
I believe `message` should be an EventHandler, so the message itself should be `message.data` as in the previous examples.
=> Fix typo in code for Example 7.

index.html
Addresses Issue #315: list of displays: should it address display name, language, etc.?
This adds an implementation note suggesting that receiving user agents advertise a user friendly display name with a locale and text direction, and controlling user agents render it using that information.
=> Adds an implementation note for advertising and rendering a user friendly display name

index.html
I find the section that defines and specifies the behavior of the default presentation request somewhat unclear in [6.2.1 Controlling user agent](https://w3c.github.io/presentation-api/#controlling-user-agent). More precisely:
1. There is no proper definition as to what the "default presentation request" represents.
2. I am unclear whether the initial value for the attribute is always `null`. I think it is, but the spec only specifies behavior when the attribute is "set by the controller". Can the attribute be set by the controlling user agent? I suppose not (at least that does not seem to make sense).
3. The text explicitly covers the case when the sandboxed presentation browsing context flag is set, but since that check is part of the "start a presentation" algorithm that gets called to …
=> Clarify the default presentation request mechanism?

index.html
This addresses Issue #303: Define that "TV" should appear as token for UA-string when presentation API is used to render on TV.  It implements the proposed resolution: add a note about feature detection through the receiver attribute.
=> Implements proposed resolution for Issue #303

index.html
Addresses Issue #337: PresentationConnectionList is not required for receiving user agents.  Implements proposed resolution:  add PresentationConnectionList to the list of interfaces to be supported by receiving user agents.
=> Implements proposed resolution for Issue #337

index.html
Addresses Issue #340: Example 5.6 doesn't need onconnect handler.  It removes the handler as connections are provided to the receiver in a connected state.
=> Addresses Issue #340

index.html
Addresses Issue #341: navigator.presentation is marked optional in WebIDL.  It implements the proposed resolution: make navigator.presentation attribute mandatory to align with the normative prose.
=> Addresses Issue #341

index.html
Addresses Issue #343: Establishing a presentation connection steps do not handle failures.  This adds an error handling case to the establish a connection algorithm.  It also removes the note about the UA later reconnecting, so that error is a terminal state.
Implements proposed resolution: For #343, move error handling steps from the start algorithm to the establish a connection algorithm, and remove the note in 6.5.1 about retrying connection establishment.
=> Add error handling to establish a presentation connection algorithm.

index.html
This creates a definition of "available presentation display" to replace the use of "compatible presentation display" and updates references accordingly.  This addresses Issue #342: Presentation display availability is not clearly defined.
=> Addresses Issue #342: Update definition of available presentation display.

index.html
Fix errors in example 5.5 like missing reconnectBtn element and move to newer ECMAScript features where it makes sense.
=> Fix example 5.5 and move to ECMAScript2015

index.html
To close out #339, this fixes &&, >,  and also moves the declaration of `reconnectBtn` to Example 3 (reconnect presentation example).
=> A couple of small fixes to the example code

index.html
Addresses Issue #366: Steps to reconnect to a presentation assume there's already a PresentationConnection.
This is editorial: the differences between steps 6-7 and 8-9 were hard to pick up without close reading.  This PR uses longer variable names and bullet lists to improve readability.
It also clarifies that in step 8, the existing connection must come from a different browsing context.
=> Clarify identities of PresentationConnection objects in reconnect() steps

index.html
Addresses Issue #361: Use USVString for URLs.
=> Replace DOMString with USVString for PresentationRequest URLs.

index.html
This PR addresses the issues noted in Issue #359 ("setting presentation.defaultRequest will have no effect" note is ambiguous).  Specifically:
1.  It clarifies that initiation of a presentation from the default request must come from the browser "chrome", not from any action of the page.
2. It lists specific steps for initiating a presentation from `start()` that check preconditions, allow the user to select a display, and return a Promise.
3. It lists specific steps for initiating a presentation from a default request that checks preconditions.
4. It clarifies that user agents that do not support initiation from a default request should ignore any value set for `navigator.presentation.defaultRequest.`
=> Adds steps for initiating presentation from default presentation request.

index.html
Addresses #365: [SameObject] for receiver seems wrong
=> Remove [SameObject] from navigator.presentation.receiver

index.html
This addresses Issue #335 by clarifying the roles of objects used by `getAvailability()`.
Specifically:
- Each `PresentationRequest` has at most one _presentation display availability_ and a _presentation availability promise_.
- The former is set to a `PresentationAvailability` object the first time it's needed.
- The latter is set to a new `Promise` the first time it's needed.
I did not use `[SameObject]` here as it did not seem appropriate per discussion in the other issue.
As far as I understand, with this clarification the example in https://github.com/w3c/presentation-api/issues/335#issue-173916158 should work by resolver order guarantees.
=> Clarifies the roles of objects for getting presentation display availability.

index.html
This addresses the comment in Issue #360 (Clarify event order when establishing a presentation connection).
=> Clarify the task source for the specification.

index.html
Addresses Issue #364: It is unclear what "If there is already an unsettled Promise from a previous call to start for the same controlling browsing context" means"
=> Clarify when a simultaneous call to start() can be rejected.

index.html
=> Move mixed content check to PresentationRequest ctor.

index.html
This addresses Issue #363: Clarify arguments to getting presentation displays availability information.
Specifically:
- Ensures that inputs to steps are written in terms of the objects that functions are called on and their arguments.
- Moves the precondition for the connection input to establishing a presentation connection steps into the steps themselves.
- Removes trailing punctuation throughout for consistency.
=> Clarifies inputs to algorithms.

index.html
Addresses Issue #382: Wrong use of "available presentation displays" in 6.4.4.
Replaces "available presentation displays" with "presentation displays" in steps 3 and 4 to monitor presentation displays.
Addresses Issue #383: Drop step 6 of getAvailability for consistency with start?
The set of new displays found by the monitor steps is empty by default.  If a new list cannot be retrieved, existing `PresentationAvailability` objects will have their value set to `false`.
=> Addresses Issues 382 and 383 on the steps to get presentation displays.

index.html
Addresses Issue #374: Determine if we need to fire a terminated event in the receiving browsing context(s).
This changes the state of connections in the presentation to `terminated` before unloading the document in the receiving browsing context.  This is in lieu of firing an `terminate` event, which seems redundant with existing events like `beforeunload`.
Note that this change will prevent messages from being sent during `beforeunload`, which actually seems like it should simplify implementations:  they can disable and tear down the communication channels immediately upon receiving a signal to terminate.
PTAL
=> Sets the state of receiving presentation connections to terminated before unload.

index.html
Addresses Issue #379: Investigate if sandboxing flag check can move to the PresentationRequest ctor.
For consistency, check the sandboxing flag in the `PresentationRequest` constructor.  Keep the checks in other functions the case the flag was unset at construction time and set later.
It may be that the sandboxing flag should be persistent, however, this does not seem to be implemented in Blink.  If that's true then we can remove the other checks later.
=> Issue #379: Adds sandboxing flag check to PresentationRequest ctor.

index.html
Addresses Issue #360: Clarify event order when establishing a presentation connection.  This uses a dedicated task source instead of the networking task source, per TAG feedback.
=> Issue #360: Adds a presentation task source

index.html
The name of an enum isn't observable, and this matches Blink's IDL. In
one place, "closeReason" is already used as a variable name.
=> Rename PresentationConnectionClosedReason to PresentationConnectionCloseReason

index.html
Addresses Issue #387: Well defined environment for nested contexts of the receiving browsing context?
This applies the restrictions placed on the receiving browsing context to child browsing contexts of that context.   It also clarifies that `navigator.presentation.receiver` should be `null` in those contexts.
Please check my terminology :)
=> Addresses Issue 387

index.html
This PR is meant to replace PR #390. It implements the changes discussed there.
Main changes:
- Prose similar to that used in the Web Bluetooth spec used for the garbage collection note for the "presentation display availability" to clarify the intent. We may want to adjust this text in #391.
- Notion of "presentation availability promise" dropped. That promise is now referenced in `getAvailability` as "an unsettled Promise from a previous call to `getAvailability` on `presentationRequest`". This avoids having to be explicit about garbage collection rules.
- Step that instructs the UA to run the monitoring algorithm no longer runs "in parallel" (see #381)
- Note added next to that step to clarify that the monitoring algorithm needs to run again even if it is still running
- The monitoring …
=> Issue #387: Monitoring algo takes pending request to start into account

index.html
Removes redundant checks from algorithms that require an already-constructed `PresentationRequest`, since it won't be possible to construct one in a sandboxed context.
=> Addresses Issue #398: Sandboxing steps in start, reconnect, getAvailability are now useless

index.html
Addresses Issue #391: Steps that re-use objects should specify the relevant settings object/Javascript Realm 
Assigns a specific ("relevant") JavaScript realm to objects that may be created in one browsing context and later vended to another.  The default ("current") realm is used for objects that are constructed anew each time.
=> Addresses Issue #391

index.html
This addresses Issue #394: Make select algo reject in ancestor and descendant browsing contexts
It checks the top-level browsing context and all descendant browsing contexts for pending calls to `start()`.
It also clarifies which browsing context is meant by "controlling browsing context" in algorithms.
=> Addresses Issue #394: Reject start() in all browsing contexts

index.html
Addresses Issue #380: Authenticity of screen selection permission is problematic in insecure contexts.
This also alters the terminology to refer to potentially trustworthy origins, to align with the current drafts of Mixed Content [1] and Secure Contexts [2].
[1] https://www.w3.org/TR/mixed-content/
[2] https://www.w3.org/TR/secure-contexts/
=> Adds a note about display of origins that are not potentially trustworthy.

index.html
Done:
- All IDL terms now have `<dfn>` in prose
- Added "simple" constructor logic for custom Events to clarify how `EventInit` dictionary members are to be used
- Added missing reference to Web Messaging spec (which defines `MessageEvent`)
- Linked terms to definition throughout the spec
- Improved support for linking to methods with parentheses, e.g. `start()`, `reconnect()`
- Occurrences of "presentation" that should link to "controlling browsing context" now effectively link to it
- Occurrences of "Presentation" that should link to the IDL definition now effectively link to it
Notes:
- There is simply no way to define an idiom "presentation" and an interface "Presentation" using ReSpec without running in all sorts of linking issues. I've hardcoded "presentation" (as an idiom) links as …
=> Issue #397 - Make sur all IDL terms have <dfn> in prose

index.html
This commit updates all HTML 5.0 references to HTML 5.1.
To help assess references stability (issue #295), the spec now also directly references the WebIDL Level 1 Recommendation, pointing out that NotAllowedError is defined in WebIDL Level 2. References to the WHATWG version of HTML for "current settings object" and "relevant settings object" now target HTML 5.1 as well.
Other changes introduced in this commit:
- Correct nesting of `<a>`, `<code>`, `<dfn>` to make sure code definitions get styled in red as expected
- ReSpec now automatically supports aliases such as "start()" for method, so dropped the now redundant alias definitions.
- Turned references incorrectly marked as informative into normative references (UUID, cookies, RFCs).
=> Issue #396: Migrate HTML 5.0 references to HTML 5.1

index.html
Publication rules require us to document changes since previous version. We've made a number of changes since publication as Candidate Recommendation in July 2016 and the list of issues and the list of commits are somewhat hard to review. I propose to add a change log section with links to issues, and to slightly update the Status of This Document section to link to it.
=> Added change log section with list of changes since first CR

index.html
This PR migrates Service Workers references from old Editor's Draft to [Service Workers 1 Working Draft](https://www.w3.org/TR/service-workers-1/).
=> Update Service Worker references

index.html
Address Issue #380: Authenticity of screen selection permission is problematic in insecure contexts
This restricts the use of Presentation API to secure contexts through the use of `[SecureContext]`.  Also:
- Mixed content check is simplified
- Examples are updated to use `https:`
- Use correct term for _a priori authenticated URL_
- Remove xref to _potentially trustworthy origin_ as it's unused
- Remove discussion of insecure origin display
=> Restrict API to secure contexts

index.html
Addresses Issue #414: Receiving browsing context needs additional flags set.
It sets the _sandboxed top-level navigation browsing context flag_ and _sandboxed modals flag_ on the receiving browsing context, to protect the integrity of the origin being presented, and to reflect implementation behavior (pending Mozilla feedback).
It also drops a reference to calling `window.close()`, as this is not allowed with the former flag set.  Instead, the presentation must call `connection.terminate()` on any `PresentationConnection`.
=> Sets top-level navigation and modal dialog flags on presentations.

index.html
The Status of This Document section also highlights the restriction to secure contexts.
=> Updated list of changes since previous CR

index.html
Followup to #415.  Adds notes to Create a Receiving Browsing Context and User Interface Guidelines around sandboxing flags.
=> Adds notes related to sandboxing flags on presentations 

index.html
See related discussion in: https://github.com/w3c/presentation-api/issues/406
***
[Preview](https://s3.amazonaws.com/pr-preview/tidoust/presentation-api/exit-criteria.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/32e1adb...tidoust:0b314ed.html)
=> Relaxed CR exit criteria to match known implementation plans

index.html
The allow-presentation sandbox attribute value and related flags have been integrated in HTML5.2 (see https://github.com/w3c/html/pull/861).
I kept things simple for now, referencing HTML 5.2 only for that flag, keeping references to HTML 5.1 otherwise. I propose to check whether we can switch all references to HTML 5.2 when we get ready to publish the spec as Proposed Recommendation.
***
[Preview](https://s3.amazonaws.com/pr-preview/tidoust/presentation-api/drop-sandboxing.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/f27dd39...tidoust:d7f1cae.html)
=> Dropped sandboxing section, referencing HTML 5.2 instead

index.html
Addresses Issue #423: Termination should also "discard" the receiving browsing context.
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/issue-423-terminate.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/b714910...3d653ff.html)
=> Add steps to discard the receiving browsing context.

index.html
Addresses issue #422: Turn SHOULD into MUST for close/terminate messages handling? 
- A UA _must_ close a connection in response to a request from the destination browsing context (either because close() was called, or that context went away).
- A UA _must_ close its connection in response to an unrecoverable network or other error.
- A controlling UA _must_ terminate a connection in response to a termination by the receiving UA.
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/issue-422-must.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/aa7c4e7...bd42352.html)
=> Change SHOULD to MUST when closing or terminating connections.

index.html
Addresses Issue #419: Behavior of a receiving user agent in reconnecting.
When a `PresentationConnection` is closed, remove it from the set of presentation controllers (and thus the `PresentationConnectionList`).
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/issue-419-discard-closed.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/aa7c4e7...68ab7d4.html)
=> Remove closed connections from the set of presentation controllers.

index.html
The charter of the Second Screen WG is explicit that the group will use the W3C Software and Document License for all its deliverable:
http://www.w3.org/2014/secondscreen/charter-2016.html#licensing
Now, that seems to have fallen through the cracks until now as drafts have actually been published under the more restrictive W3C Document License.
***
[Preview](https://s3.amazonaws.com/pr-preview/tidoust/presentation-api/fix-license.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/38f2399...tidoust:f27622b.html)
=> Tell ReSpec to use W3C Software and Document License for the spec

index.html
Addresses Issue #421: Relax `terminate` algorithm to deal with other states?
This allows termination of a presentation by a connection in the `connecting` state in a controlling browsing context.
Presumably if a connection has not been established to the presentation screen, then the connection can be aborted.  If the connection has been established and the presentation started, but the `connected` state change has not yet occurred, that connection can be used to abort or terminate the presentation.
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/issue-421-terminate-reconnect.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/38f2399...e2c6d68.html)
=> Allow termination via connections in a connecting state.

index.html
Addresses Issue #345: Introduction could use come copy editing.
This updates the prose in the introduction to use more precise language and improve style.
It makes minor editing improvements to non-normative notes and the security and privacy section.
It also adds acknowledgements of registered trademarks used in the specification.
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/issue-345-editing.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/6c3a68f...fe784b4.html)
=> Copy editing of non-normative text

index.html
Working Group is now officially named "Second Screen Working Group".
***
[Preview](https://s3.amazonaws.com/pr-preview/tidoust/presentation-api/fix-groupname.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/ba660b0...tidoust:579e6fe.html)
=> Fix group name and update changelog

index.html
* Update references to the latest Permissions API
* Link to the TR version of the WebRTC API
* Fix nfc-forum.org certificate warning by downgrade
PTAL @mfoltzgoogle @tidoust.
(To publish a spec in TR space, there must not be any broken links.)
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/fix-broken-links.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/58b3159...4d4beb5.html)
=> Fix broken fragments reported by Link Checker

CONTRIBUTING.md, LICENSE.md, w3c.json
Add LICENSE with reference to Doc & Sw license
Complete CONTRIBUTING.md with instructions for attributions
Document owner of repo in w3c.json
=> Align repo administrivia with W3C baseline

index.html
Addresses Issue #434: In receiver page, sandboxing flags do not fully block top-level navigation.
This adds two more specific requirements:
- Top level browsing context can't navigate itself to a different URL, except for fragment navigation.
- Nested browsing contexts can't navigate the top level browsing context by setting the _sandboxed top-level navigation browsing context flag_.
There might still be work to do here.  For example, this doesn't directly address server initiated navigation (HTTP redirects).  If we really want to restrict the scope of where the top level document can go, we may want to see if there are applicable mechanisms from Content Security Policy instead of (or in addition to) this language.
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/issu …
=> Clarifies restrictions on navigation in receiving browsing contexts.

index.html
https://github.com/heycam/webidl/issues/365
Fix #437
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/webidl-exposed.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/2ec8ffa...72cfca6.html)
=> Use [Exposed=Window]

index.html
@mfoltzgoogle, I noticed ReSpec logs the following console warnings:
```
The `for` and `dfn-for` attributes are deprecated.
Please use `data-dfn-for` instead. See developer console.
```
(Since these warnings were not surfaced through the ReSpec UI, I missed them in my initial patch https://github.com/w3c/presentation-api/commit/35f4aa990713d3a3441714ce8bf9c3bc58463094)
This PR fixes these remaining warnings in commit bcdd827
In a separate commit 7bd0067 I tidied the source to bring the more recent changes in line with the conventions.
All changes are purely editorial and under the hood, no changes to the rendered output.
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/fix-respec-console-warnings.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/ …
=> Fix ReSpec console warnings

index.html
This updates the `Blob` reference to match the latest in the File API spec.
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/blob-ref.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/b29f405...9e89a15.html)
=> Update Blob reference

index.html
This PR addresses #446.
- A URL with an unsupported scheme is ignored in constructing a PresentationRequest.
***
<a href="https://pr-preview.s3.amazonaws.com/tomoyukilabs/presentation-api/pull/447.html" title="Last updated on Mar 23, 2018, 10:17 AM GMT (cca5eb2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/447/0919461...tomoyukilabs:cca5eb2.html" title="Last updated on Mar 23, 2018, 10:17 AM GMT (cca5eb2)">Diff</a>
=> Ignore a URL with an unsupported scheme

index.html
Addresses Issue #451: Add sample code for single controller to multiple presentations.
Adds a code sample showing how the developer can create a second presentation, from the same controlling page.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/453.html" title="Last updated on Jun 14, 2018, 8:48 PM GMT (18f1e28)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/453/b439c16...18f1e28.html" title="Last updated on Jun 14, 2018, 8:48 PM GMT (18f1e28)">Diff</a>
=> Adds sample code for starting a 2nd presentation.

index.html
See https://html.spec.whatwg.org/multipage/web-sockets.html#binarytype.
Fixes https://github.com/w3c/presentation-api/issues/456.
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/presentation-api/pull/457.html" title="Last updated on Aug 8, 2018, 1:05 PM GMT (3470b52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/457/2a686db...foolip:3470b52.html" title="Last updated on Aug 8, 2018, 1:05 PM GMT (3470b52)">Diff</a>
=> Remove BinaryType enum (already in HTML)

index.html
Fix ReSpec errors reported for references to "1-UA mode" and "2-UA mode"; these are defined terms and don't need to be manually linked.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/458.html" title="Last updated on Aug 30, 2018, 11:59 PM GMT (5bfe300)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/458/c0cea69...5bfe300.html" title="Last updated on Aug 30, 2018, 11:59 PM GMT (5bfe300)">Diff</a>
=> Fix respec errors.

index.html
This reverts commit c0cea69ed17a5584c4486a3551f8e6bb801203fe, landed to address Issue #456.
That commit introduced ReSpec errors:
```
Duplicate definitions of 'arraybuffer' at: 1.
Duplicate definitions of 'blob' at: 1.
```
FYI @foolip
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/459.html" title="Last updated on Aug 31, 2018, 12:04 AM GMT (aa3860c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/459/c0cea69...aa3860c.html" title="Last updated on Aug 31, 2018, 12:04 AM GMT (aa3860c)">Diff</a>
=> Revert "Remove BinaryType enum (already in HTML) (#457)"

index.html
Addresses issue #449: Behavior of window.reload() on presentation receiver page.
Permit presentation receiver pages to be reloaded, which assists developers using the Presentation API.  Such pages will need to be manually reconnected.
Some changes are because I upgraded to Tidy 5.6.17 which has a few minor differences in HTML processing.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/454.html" title="Last updated on Jun 14, 2018, 9:46 PM GMT (f2fe470)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/454/b439c16...f2fe470.html" title="Last updated on Jun 14, 2018, 9:46 PM GMT (f2fe470)">Diff</a>
=> Address issue #449.

index.html
This addresses Issue #435, by adding a brief explanation before each section of example code.  It would be helpful for a second pair of eyes to point out anything that is still not obvious and could be improved.
It also addresses some ReSpec errors that have crept in, apparently because event names are not defined in WebIDL, and also conflict with function definitions.  We'll just leave them unlinked for simplicity.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/460.html" title="Last updated on Mar 26, 2019, 6:08 PM UTC (34ef5ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/460/65b85d4...34ef5ea.html" title="Last updated on Mar 26, 2019, 6:08 PM UTC (34ef5ea)">Diff</a>
=> Add explanatory text to examples.

build/tidyconfig.txt, index.html
This addresses feedback in Issue #455, to link navigation behavior to the HTML 5.1 navigation steps, and clarify how the receiving user agent should respond.
There's also a bunch of changes from attempting to run tidy-html5 which I'll clean up in another commit on this PR.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/461.html" title="Last updated on Apr 5, 2019, 6:16 PM UTC (45813d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/461/ff5a520...45813d3.html" title="Last updated on Apr 5, 2019, 6:16 PM UTC (45813d3)">Diff</a>
=> Clarify self-navigation behavior in a presentation.

build/tidyconfig.txt, index.html
This just runs the latest version of tidy-html5 on the spec.  
Most of the changes are just indentation and line wrapping.
However, the current version of tidy-html5 adds an xmlns to the `<html>` tag and also wraps inline styles in `CDATA` blocks.  I will check that this doesn't trip up ReSpec or the spec validator before landing.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/463.html" title="Last updated on Apr 5, 2019, 10:44 PM UTC (04b138c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/463/fad8923...04b138c.html" title="Last updated on Apr 5, 2019, 10:44 PM UTC (04b138c)">Diff</a>
=> [Editorial] Runs tidy-html5.

index.html
Apart from direct mapping:
- "firing an event" concept moved to [DOM]
- "firing a simple event named e" concept replaced with "fire an event" in https://github.com/whatwg/html/issues/1887
- "sandboxed top-level navigation browsing context flag" is now forked into "with user gesture" and "without user gesture",
"without user gesture" seems appropriate here. Historical context: https://github.com/w3c/presentation-api/issues/414
Fix #464
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/465.html" title="Last updated on Jun 27, 2019, 7:22 PM UTC (f552cca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/465/b9dd345...f552cca.html" title="Last updated on Jun 27, 2019, 7:22 PM UTC (f552cca)">Diff</a>
=> Update [HTML51] and [HTML52] references to [HTML]

index.html
This PR fixes a few ReSpec errors:
- Fix `Navigator` reference
- Use constructor operations (see #466)
***
<a href="https://pr-preview.s3.amazonaws.com/chrisn/presentation-api/pull/469.html" title="Last updated on Sep 5, 2019, 3:12 PM UTC (09ba211)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/469/5f5a8f3...chrisn:09ba211.html" title="Last updated on Sep 5, 2019, 3:12 PM UTC (09ba211)">Diff</a>
=> Update WebIDL usage and fix Respec errors

index.html
The Presentation API defined the `BinaryType` enumeration because it was referencing HTML5. That's no longer needed because the spec now references HTML LS, which defines the enumeration.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/presentation-api/pull/473.html" title="Last updated on Sep 28, 2019, 9:11 AM UTC (d7bfc1f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/473/a76a31e...tidoust:d7bfc1f.html" title="Last updated on Sep 28, 2019, 9:11 AM UTC (d7bfc1f)">Diff</a>
=> Drop BinaryType enum definition

build/tidyconfig.txt, index.html
- Adds warn-proprietary-attributes:  no to the tidy spec (otherwise it refuses to process the spec)
- Re-run tidy resulting in some line wrapping fixes.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/481.html" title="Last updated on Jul 7, 2020, 5:54 PM UTC (609d319)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/481/1d9fcf3...609d319.html" title="Last updated on Jul 7, 2020, 5:54 PM UTC (609d319)">Diff</a>
=> Fix some HTML tidy formatting

index.html
The update tells ReSpec to look for Navigator in the HTML spec. It also updates the URL of the ReSpec script. Coupled with #482, this should fix ReSpec errors.
Unrelated, the update also reduces the information provided for the boilerplate text to a minimum by asking Respec to fetch the group info itself.
Note the `xref` list will need to be completed once the Presentation API starts using automatic cross-ref linking features instead of maintaining definitions in a separate "Terminology" section as currently done. Relying on the automatic cross-ref linking feature is recommended to detect cross-references to concepts that groups actually did not plan to export to other specs, as well as terms that may no longer exist in other specs. I'll prepare another PR for that.
***
<a …
=> Editorial: fix link to Navigator and update Respec URL

index.html
This addresses Issue #338: Can the same browsing context act as a controller and receiver?
This adds a note just clarifying that the spec allows a receiving browsing context (created by starting one presentation) to start a second presentation, and thus become a controlling browsing context as well.
Not sure if this belongs in the main body of the specification, as this is a clarification and not a new requirement, but would be fine with putting it there as well.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/487.html" title="Last updated on Oct 26, 2020, 6:33 PM UTC (b651cbd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/487/7cc74aa...b651cbd.html" title="Last updated on Oct 26, 2020, 6:33 PM UTC (b651cbd)">Diff</a>
=> Add note about controlling browsing contexts.

index.html
[This PR cannot be merged as-is. Some discussion needed on the treatment of the remaining errors]
Since the specification was written, authoring tools have made a lot of progress on cross-references support, and groups have become better at differentiating between definitions that should remain internal to a given specification (think "private" in object oriented languages) and those that the group commits to maintain over time and that can be referenced by other specifications (think "public").
This update uses the `xref` feature of Respec throughout the spec, and drops all indirect definitions that were in the Terminology section that can now be taken care of automatically by Respec. Some of them cannot be because the underlying specifications are not known to Respec.
Some of the …
=> Switch to automatic cross-references

index.html
This just re-ran tidy on the spec to clean up line wrapping.  Should be whitespace only changes.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/490.html" title="Last updated on Oct 30, 2020, 7:04 PM UTC (2d740d9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/490/809fba0...2d740d9.html" title="Last updated on Oct 30, 2020, 7:04 PM UTC (2d740d9)">Diff</a>
=> Re-runs tidy-html5 on the current spec.

index.html
This updates the Presentation API changelog from PR #429 - PR #473.  I'll also add PR #487 once it is merged.
This is to facilitate the publication of a Candidate Recommendation Draft (Issue #488).
I skipped a few PRs that were about reformatting, or fixing ReSpec links.  If there are any relevant PRs I missed, let me know!
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/489.html" title="Last updated on Oct 30, 2020, 7:11 PM UTC (36a5e6e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/489/fd33764...36a5e6e.html" title="Last updated on Oct 30, 2020, 7:11 PM UTC (36a5e6e)">Diff</a>
=> Updates changelog to prepare for CRD publication.

index.html
301 links need to be updated per publication rules.
The `wpt.live` domain should be more stable than `w3c-test.org`.
This update also fixes an HTML markup error: `link-for` should have been `data-link-for` (otherwise it remains as `link-for` in the generated page, which is invalid HTML). In practice, the attribute was not needed in the section where it appeared. This update removes it.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/presentation-api/pull/492.html" title="Last updated on Nov 4, 2020, 11:24 AM UTC (a1c52a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/492/736e459...tidoust:a1c52a5.html" title="Last updated on Nov 4, 2020, 11:24 AM UTC (a1c52a5)">Diff</a>
=> Update 301 links and test suite URL

index.html
Use of inclusive terminology is strongly encouraged, see:
https://w3c.github.io/manual-of-style/#inclusive
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/presentation-api/pull/493.html" title="Last updated on Nov 4, 2020, 11:33 AM UTC (5bac02f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/493/736e459...tidoust:5bac02f.html" title="Last updated on Nov 4, 2020, 11:33 AM UTC (5bac02f)">Diff</a>
=> Switch to neutral "they" for user

index.html
The Status of This Document section was still talking about changes since the Candidate Recommendation published in 2016. This update adjusts the text to mention main normative changes since the 2017 version, and to point at the right list of changes.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/presentation-api/pull/491.html" title="Last updated on Nov 4, 2020, 6:28 PM UTC (dfee939)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/491/736e459...tidoust:dfee939.html" title="Last updated on Nov 4, 2020, 6:28 PM UTC (dfee939)">Diff</a>
=> Update SOTD to mention main normative changes since last CR

index.html
The concept of "application cache" was completed removed from HTML 6 days ago:
https://github.com/whatwg/html/commit/e4330d510a1d05e1f5f84707c9d6dcec97db94b8
The notion of "a priori authenticated URL" was dropped in mixed content, and is to be replaced by "potentially trustworthy URL" in Secure Contexts.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/presentation-api/pull/495.html" title="Last updated on Dec 7, 2020, 3:11 PM UTC (76afce7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/495/ffea4da...tidoust:76afce7.html" title="Last updated on Dec 7, 2020, 3:11 PM UTC (76afce7)">Diff</a>
=> Fix refs to "a priori authenticated URL" and "application cache"

index.html
The [Fire an event](https://dom.spec.whatwg.org/#concept-event-fire) and [Create an event](https://dom.spec.whatwg.org/#concept-event-create) algorithms defined in the DOM spec now create trusted events by default, so no need to define a "trusted event" term anymore.
Also, the concept of "default action" for an event no longer exists, see:
https://dom.spec.whatwg.org/#action-versus-occurance
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/presentation-api/pull/496.html" title="Last updated on Dec 7, 2020, 5:25 PM UTC (25a947d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/496/ffea4da...tidoust:25a947d.html" title="Last updated on Dec 7, 2020, 5:25 PM UTC (25a947d)">Diff</a>
=> Adjust terminology for events

index.html
The `BinaryType` type is defined in WebSockets and WebSockets is no longer part of the HTML spec.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/presentation-api/pull/501.html" title="Last updated on Apr 14, 2022, 4:04 PM UTC (afeb098)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/501/395194c...tidoust:afeb098.html" title="Last updated on Apr 14, 2022, 4:04 PM UTC (afeb098)">Diff</a>
=> Add the websockets spec to the list of xref sources

index.html
This logic is remove method when reconnect.
Target method name is `onclose` .
```js
connection.onclose = _ => {
connection = null;
showDisconnectedUI();
};
```
But, this logic remove `onclosed` method.
```js
// Disconnect from existing presentation, if not attempting to reconnect
if (connection && connection != newConnection && connection.state != 'closed') {
connection.onclosed = undefined;
connection.close();
}
```
***
<a href="https://pr-preview.s3.amazonaws.com/youkinjoh/presentation-api/pull/508.html" title="Last updated on Dec 14, 2022, 2:37 AM UTC (96ae513)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/508/e142aef...youkinjoh:96ae513.html" title="Last updated on Dec 14, 2022, 2:37 AM UTC (96ae513)">Diff</a>
=> typo remove method

index.html
See Issue #509 for background.   This PR is intended to fix the current crop of ReSpec errors and warnings.  
WhatWG HTML makes the following recommendation,
> Modern specifications should avoid using the browsing context concept in most cases, unless they are dealing with the subtleties of browsing context group switches and agent cluster allocation. Instead, the Document and navigable concepts are usually more appropriate.
In the future we may want to update the spec to refer to current concepts like navigables and traversables, instead of browsing contexts.  However that is out of scope for right now.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/514.html" title="Last updated on Jan 19, 2023, 2:48 PM UTC (e7f90b9)">Preview</a> | <a …
=> Update cross references to HTML.

index.html
`{string: '你好，世界!', lang: 'zh-CN'}` is not parsable to JSON.
```js
// controller.html
connection.send("{string: '你好，世界!', lang: 'zh-CN'}");
// presentation.html
var messageObj = JSON.parse(message.data);
```
And, drop `body` property.
```js
document.appendChild(spanElt);
```
***
<a href="https://pr-preview.s3.amazonaws.com/youkinjoh/presentation-api/pull/511.html" title="Last updated on Dec 26, 2022, 7:22 AM UTC (837c343)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/511/cb625d4...youkinjoh:837c343.html" title="Last updated on Dec 26, 2022, 7:22 AM UTC (837c343)">Diff</a>
=> debug `EXAMPLE 7`

index.html
RFC 9110 (HTTP Semantics) has obsoleted the RFC for HTTP 1.1.
Update term references to point to RFC 9110.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/518.html" title="Last updated on Oct 11, 2023, 10:47 PM UTC (c9243cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/518/cb625d4...c9243cf.html" title="Last updated on Oct 11, 2023, 10:47 PM UTC (c9243cf)">Diff</a>
=> Update references to HTTP.

index.html
This PR updates remaining references to external concepts/terms to use the `data-cite` attrribute.  Since these are in non-W3C in specs, I didn't check for xrefs for these terms.  I also didn't touch HTML cross references.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/519.html" title="Last updated on Oct 13, 2023, 9:29 PM UTC (3e27e85)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/519/2ef78f7...3e27e85.html" title="Last updated on Oct 13, 2023, 9:29 PM UTC (3e27e85)">Diff</a>
=> Convert remaining external terms to use data-cite.

index.html
ReSpec now references the `httpwg.org` versions of RFCs when they exist. Unfortunately, these versions use different fragment identifiers.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/520.html" title="Last updated on Nov 24, 2023, 2:55 PM UTC (53e7ae6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/520/a128d1e...53e7ae6.html" title="Last updated on Nov 24, 2023, 2:55 PM UTC (53e7ae6)">Diff</a>
=> Update now broken RFC links

index.html
Possible fix to #521.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/522.html" title="Last updated on Aug 23, 2024, 5:47 PM UTC (cc16863)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/522/3a9454f...cc16863.html" title="Last updated on Aug 23, 2024, 5:47 PM UTC (cc16863)">Diff</a>
=> Mark Dominik Rottsches as a former editor.

index.html
Addresses Issue #523 by specifically queuing a global task when promises are resolved or events are fired from parallel steps.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/524.html" title="Last updated on Sep 19, 2024, 6:31 PM UTC (0fb1088)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/524/74d1a41...0fb1088.html" title="Last updated on Sep 19, 2024, 6:31 PM UTC (0fb1088)">Diff</a>
=> Fix task queueing.

index.html
Closes Issue #507 by always returning a new Promise from `PresentationRequest.getAvailability()`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/pull/525.html" title="Last updated on Oct 7, 2024, 5:33 PM UTC (4e6d7e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/525/214830c...4e6d7e3.html" title="Last updated on Oct 7, 2024, 5:33 PM UTC (4e6d7e3)">Diff</a>
=> Always return a new Promise from getAvailability().
