Overview.src.html
index.html
xrefs/presentation.json

HTML preview at: http://rawgit.com/anssiko/presentation-api/reorg/index.html
The green boxes are to ease the review, they highlight the gaps and contain some boilerplate text and proposals.
(And, I should say, sorry for the monolithic commit.)

Move prose below the corresponding IDL blocks; other editorial changes

---

index.html

Fixed with:
<https://bitbucket.org/ms2ger/anolis/issue/16/force-sorted-attributes>

Editorial: sort attributes alphabetically from A to Z.

---

Overview.src.html
index.html

* CSS before "open issue"
* Case for "Multiplayer Gaming"
* Security and Privacy Considerations

Minor edits

---

Overview.src.html
index.html

This PR contains new draft of the example section as discussed in issue #42

Make the Example section more concise  (Issue #42)

---

Overview.src.html
index.html

Declare DOMException types for rejected Promises

---

Overview.src.html
index.html

Mostly some formatting changes to fix the structure of the spec (and ease modifying it).

Fixed the structure of <section> tags in the spec HTML

---

Overview.src.html
index.html
xrefs/presentation.json

See https://github.com/w3c/presentation-api/issues/26 for details.
I also fixed the <section> structure of the document which was misaligned and updated xrefs/presentation.json (not sure if I had to do that or not).

Added defaultsessionstart and default-presentation <link> to the spec

---

Overview.src.html
index.html

Addresses Issue #95
* Make sure we designate a target for the `availablechange` event
* Fix confusion between event and handler

Fix bugs in availablechange event

---

Overview.src.html
index.html
xrefs/presentation.json

Related: https://github.com/w3c/presentation-api/pull/100

Set presentations issue 65

---

Overview.src.html
index.html

Rebased version of https://github.com/w3c/presentation-api/pull/103

Fixes #102: Fix bugs related to PresentationSession.url attribute

---

Overview.src.html
index.html

Fix for the issue https://github.com/w3c/presentation-api/issues/102.

Removed references to PresentationSession.url attribute (issue #102).

---

Overview.src.html
index.html
xrefs/presentation.json

Closes w3c/presentation-api#65.

Simplify algorithm prose for starting, joining, establishing connection; use common idioms

---

Overview.src.html
index.html

Fix send algorithm

---

Overview.src.html
index.html

Addendum to PR #126 to update the link to the power saving non functional requirement.

Update href for power saving requirement

---

uc-req.md

Adding new use case with multiuser Pictionary game, https://github.com/w3c/presentation-api/issues/68

Added Pictionary use case

---

uc-req.md

A copy editing pass incorporating changes from PR #131 by @obeletski. 
- Added paragraph breaks
- Made terminology more consistent
- Use active voice/present tense

Obeletski new usecase issue 68

---

Overview.src.html
index.html

Based on PR #129 by @obeleski:
- Merged to head
- Updated text to reflect suggestion

Obeletski messaging between sessions issue 121

---

Overview.src.html
index.html

Update to messaging section to reflect the fact that messaging is happening between presenting and controlling contexts, https://github.com/w3c/presentation-api/issues/121.

Update to messaging section

---

index.html

This ought to fix mixed content problems on https://w3c.github.io/presentation-api/

Fetch respec over HTTPS

---

index.html

- Update start and join algorithms to fire the sessionconnect event.
- Copy editing of the description of setting a default request.
- Other minor edits.

Editorial changes to pull request #146

---

index.html
uc-req.md

- Fix bug in WebIDL for PresentationRequest.join().
- Add a use case for presentation to multiple screens, locally and remotely.

Make changes suggested by @sicking

---

index.html

Mention 1-UA and 2-UA cases explicitly in the introduction

---

index.html

Resolving the getAvailability() call with the currently known status. Thanks to @foolip for catching the mistake.

Resolve getAvailability with current status.

---

index.html

Rename PresentationSession.join() to reconnect().

---

index.html

This is basically changing "title=" to "data-lt=".

Editorial: fix the the spec warnings.

---

index.html

A PR with some editorial changes on behalf of timeless. For the context, see: https://lists.w3.org/Archives/Public/public-secondscreen/2015Aug/0147.html

Address timeless' editorial feedback

---

index.html

Fix respec warnings.

---

uc-req.md

Latest renamed "presenting browsing context" to "receiving browsing context". So should change it which is file called "uc-req.md".

Rename "presenting browsing context" to "receiving browsing context" on "uc-req.md" file.

---

index.html

Fix up Grammar error about EXAMPLE6.

Fix up wrong codes about "EXAMPLE6"

---

index.html

The {title, file name} of EXAMPLE 6 lack unity.

Change EXAMPLE 6 for title unity.

---

index.html

Add some context about terminate with PresentationConnection.

Modify some context about terminate.

---

index.html

Some editorial changes and clarifications that I spotted while reviewing the first half of the spec.

Editorial changes

---

index.html

#210 , Drop disconnectController() on EXAMPLE 5.

Drop disconnectController() on EXAMPLE 5.

---

index.html

Manual merge of PR #234

---

index.html

Fix https://github.com/w3c/presentation-api/issues/217

Make all enum values lowercase for consistency

---

index.html

- Define "send a termination signal" and "send a termination confirmation signal"
- Add section "Reacting to a termination confirmation signal in a controlling browsing context"
- Misc editorial and tidy

Editorial changes to termination conditions

---

index.html

Remove redundant paragraph.

---

index.html

This commit updates the Status of This Document section, in preparation for the publication of a new Working Draft, to describe the updates made to the document since last time we published in February.

Detailed changes since last WD in SOTD

---

index.html

add detailed error handling for receiver

---

index.html

This updates PR #310 by @mounirlamouri with suggested wording, addressing Issue #293: defaultRequest text should explicitely mentions iframes that have presentation disabled from sandboxing.
PTAL

Updates PR #310

---

index.html

* Issue #328 - DOMString[] is not valid Web IDL
* Issue #327 - Behavior of new PresentationRequest([]) should be defined
* Issue #324 - PresentationConnectionClosedEvent should be PresentationConnectionCloseEvent
* Issue #323 - "SHOULD act as if " is unclear

Some editorial fixes suggested by GitHub issues

---

index.html

Addresses Issue #329: specify the prohibits mixed security contexts algorithm for multiple presentation URLs
@schien PTAL

Update security check step to handle multiple URLs.

---

index.html

Addresses Issue #344: Spec for PresentationConnectionCloseEvent closeMessage conflicts with note.
This implements the proposed resolution: update close message examples to conform to spec.

Implements proposed resolution for Issue #344.

---

index.html

Addresses Issue #346: Clarify presentation ID generation requirements.  It implements the proposed resolution by following the language from Media Capture and Streams [1].
[1] https://www.w3.org/TR/mediacapture-streams/#widl-MediaStream-id

Addresses Issue #346

---

index.html

Addresses Issue #407.  This doesn't change the algorithm, just aligns the IDL with the supposed requirements of WebIDL-2.

Remove [SameObject] from receiver.connectionList

---

index.html

Proposed fix to #408.
@mfoltzgoogle @tidoust PTAL.

Fix WebIDL references

---

index.html

This PR makes a couple of small changes to the Introduction section to improve readability.
***
[Preview](https://s3.amazonaws.com/pr-preview/chrisn/presentation-api/chrisn/introduction.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/presentation-api/4948aed...chrisn:993beec.html)

Minor changes to Introduction section

---

CONTRIBUTING.md
index.html

***
<a href="https://pr-preview.s3.amazonaws.com/foolip/presentation-api/pull/452.html" title="Last updated on Jun 12, 2018, 9:57 AM GMT (6ccf837)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/452/092052c...foolip:6ccf837.html" title="Last updated on Jun 12, 2018, 9:57 AM GMT (6ccf837)">Diff</a>

Update web-platform-tests URLs

---

ECHIDNA
index.html

***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/presentation-api/pull/494.html" title="Last updated on Nov 5, 2020, 3:43 PM UTC (ba136c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/494/c371999...tidoust:ba136c0.html" title="Last updated on Nov 5, 2020, 3:43 PM UTC (ba136c0)">Diff</a>

Update metadata for automated publication with Echidna

---

index.html

`this` variable pointed `window` object in this context.
```js
var addConnection = function(connection) {
this.onmessage = function (message) {
if (message.data == "say hello")
this.send("hello");
};
};
```
***
<a href="https://pr-preview.s3.amazonaws.com/youkinjoh/presentation-api/pull/513.html" title="Last updated on Dec 27, 2022, 1:11 AM UTC (3f5d27e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/presentation-api/513/cb625d4...youkinjoh:3f5d27e.html" title="Last updated on Dec 27, 2022, 1:11 AM UTC (3f5d27e)">Diff</a>

debug `EXAMPLE 6`
